Error that occurs when secondary is pinging when primary is posting to it

Exception happened during processing of request from ('127.0.0.1', 60404)
----------------------------------------
127.0.0.1 - - [11/Apr/2016 17:52:55] "GET /?clientPort=7001&version=7&clientRank=Secondary HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Users\Vincent\Anaconda\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Vincent\Anaconda\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Vincent\Anaconda\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Vincent\Anaconda\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "C:\Users\Vincent\Anaconda\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "C:\Users\Vincent\Anaconda\lib\socket.py", line 283, in close
    self.flush()
  File "C:\Users\Vincent\Anaconda\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine